chat/urls.py
from django.urls import path
from .views import index, room

urlpatterns = [
    path('', index, name='index'),
    path('<str:room_name>/', room, name='room'),
]

custom_auth/urls.py
from django.urls import path
from .views import *


app_name = 'custom_auth'

urlpatterns = [
    path('registration/',
         RegistrationUserView.as_view(),
         name='registration'),

    path('login/vk/',
         login_vk,
         name='login_vk'),

    path('login/<str:error>',
         CustomLoginView.as_view(),
         name='login_error'),

    path('login/',
         CustomLoginView.as_view(),
         name='login'),

    path('logout/',
         CustomLogoutView.as_view(),
         name='logout'),

    path('password_reset/',
         CustomPasswordResetView.as_view(),
         name='password_reset'),

    path('reset/<uidb64>/<token>/',
         CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('reset/done/',
         CustomPasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('reset/complete/',
         CustomPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

]

demidovsite/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import *
from python_exercise.views import *

# from rest_framework import routers
# from .views import UserViewSet, GroupViewSet


# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
# router.register(r'groups', GroupViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('custom_auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('python_exercise.urls')),
    path('api-auth',
         include('rest_framework.urls', namespace='rest_framework')),
    path('rest/', include('snippets.urls')),
    path('chat/', include('chat.urls')),
]


# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = page_not_found

custom_auth/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    email = models.EmailField()

    class Meta:
        ordering = ('id',)


class UserData(models.Model):
    user = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, null=False, verbose_name='Пользователь')
    photo_url = models.CharField(
        verbose_name='Фотография', max_length=255, blank=True, null=True)

    def __str__(self):
        return 'Данные для ' + str(self.user)

    def get_absolute_url(self):
        return self.photo_url

    class Meta:
        verbose_name = 'Данные пользователя'
        verbose_name_plural = 'Данные пользователя'
        ordering = ('id',)

custom_auth/forms.py
from django import forms
from .models import *
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordResetForm, SetPasswordForm
from .models import *
from .models import CustomUser as User


#  === Форма создания нового пользователя =====================
class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label='Логин*:',
                               max_length=100,
                               required=True,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': '',
                                          'type': 'text',
                                          'id': 'user_name'
                                          }
                               ))

    first_name = forms.CharField(label='Имя*:',
                                 max_length=100,
                                 required=True,
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control',
                                            'placeholder': '',
                                            'type': 'text',
                                            'id': 'first_name'
                                            }
                                 ))

    last_name = forms.CharField(label='Фамилия:',
                                max_length=100,
                                required=False,
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control sss',
                                           'placeholder': '',
                                           'type': 'text',
                                           'id': 'last_name'
                                           }
                                ))

    email = forms.EmailField(label='Email*:',
                             max_length=254,
                             required=True,
                             widget=forms.TextInput(
                                 attrs={'class': 'form-control',
                                        'placeholder': '',
                                        'type': 'text',
                                        'id': 'email_address'
                                        }
                             ))

    password1 = forms.CharField(
        label="Пароль*:",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'align': 'center',
            'placeholder': ''
        }),
    )

    password2 = forms.CharField(
        label="Подтверждение пароля*:",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'align': 'center',
            'placeholder': ''
        }),
    )

    class Meta:

        model = User

        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2', )

#  ======================================================================
#  === Форма входа для пользователя ============================================


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label="Логин:",
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'align': 'center',
            'placeholder': ''
        }),
    )

    password = forms.CharField(
        label="Пароль:",
        widget=forms.PasswordInput(attrs={
            'id':'password',
            'class': 'form-control',
            'autocomplete': 'new-password',
            'type': 'password',
            'align': 'center',
            'placeholder': ''
        }),
    )

#  ======================================================================
#  === Форма ввода почты для сброса пароля ==============================


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label='Email указанный при регистрации:',
                             max_length=254,
                             required=True,
                             widget=forms.TextInput(
                                 attrs={'class': 'form-control',
                                        'placeholder': 'email address',
                                        'type': 'text',
                                        'id': 'email_address'
                                        }
                             ))

#  ======================================================================
#  === Форма сброса пароля ==============================================


class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="Новый пароль",
        label_suffix=':',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'autocomplete': 'new-password',
            'type': 'text',
            'align': 'center',
            'placeholder': ''
        }),
        help_text=password_validation.password_validators_help_text_html()
    )

    new_password2 = forms.CharField(
        label="Подтверждение пароля",
        label_suffix=':',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'autocomplete': 'new-password',
            'type': 'password',
            'align': 'center',
            'placeholder': ''
        }),
    )

custom_auth/views.py
import hashlib
import html
import logging
from pprint import pprint
from urllib.parse import unquote

from demidovsite.settings import *
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView

from .forms import *
from .models import *


class RegistrationUserView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'custom_auth/registration.html'
    success_url = reverse_lazy('custom_auth:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        return context


class CustomLoginView(LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'custom_auth/login.html'
    slug_url_kwarg = 'error'

    redirect_authenticated_user = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = 'Вход'
        if context['form'].errors:
            context['form_errors'] = context['form'].errors['__all__']

        try:
            context['login_vk_error'] = self.kwargs['error']
        except:
            pass

        return context

    def get_success_url(self):
        url = self.request.POST.get('next')
        if not url:
            url = reverse_lazy('python_exercise:home')

        return url


class CustomLogoutView(LogoutView):
    template_name = 'custom_auth/logged_out.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Выход'
        return context


class CustomPasswordResetView(PasswordResetView):
    form_class = CustomPasswordResetForm
    success_url = reverse_lazy('custom_auth:password_reset_done')
    template_name = 'custom_auth/password_reset_form.html'
    email_template_name = 'custom_auth/password_reset_email.html'

    def __init__(self, *args, **kwargs):
        return PasswordResetView.__init__(self, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Сброс пароля'
        return context

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = CustomSetPasswordForm
    success_url = reverse_lazy('custom_auth:password_reset_complete')
    template_name = 'custom_auth/password_reset_confirm.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Сброс пароля'
        return context


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'custom_auth/password_reset_done.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Сброс пароля'
        return context


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'custom_auth/password_reset_complete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Сброс пароля'
        return context


def login_vk(request):
    if request.method != 'GET':
        # url = request.path
        # logging.warning(f'{url = } Method not GET')
        raise Http404('Method not GET')
    try:
        uid = request.GET['uid']
        user_hash_hex = request.GET['hash']
        first_name = request.GET['first_name']
        hash_calc = hashlib.md5(APP_ID_VK.encode('utf-8')
                                + uid.encode('utf-8')
                                + SECRET_KEY_VK.encode('utf-8'))
        if hash_calc.hexdigest() != user_hash_hex:
            raise Exception('Invalid hash')
    except Exception:
        return redirect(reverse('custom_auth:login_error',
                                kwargs={'error': 'no-data'}))

    last_name = request.GET.get('last_name', '')
    photo_url = request.GET.get('photo', '')
    photo_url_small = request.GET.get('photo_rec', '')
    photo_url_small = html.unescape(unquote(photo_url_small))

    if not last_name or not photo_url or not photo_url_small:
        logger = logging.getLogger('demidovsite')
        logger.warning('One of the following is missing'
                       f'last_name = {last_name}, photo_url = {photo_url}, photo_url_small = {photo_url_small }')

    user = authenticate(username=uid, password=user_hash_hex)
    if user is None:
        # Создаем пользователя

        user = CustomUser.objects.create()
        user.username = uid
        user.set_password(user_hash_hex)
        user.first_name = first_name
        user.last_name = last_name
        userdata = UserData.objects.create(
            user=user, photo_url=photo_url_small)
        userdata.save()
        user.save()

    else:
        user.first_name = first_name
        user.last_name = last_name
        user.userdata.photo_url = photo_url_small
        user.userdata.save()
        user.save()

    login(request, user)
    return redirect(reverse('python_exercise:home'))

custom_auth/templates/custom_auth/logged_out.html
{% extends 'python_exercise/base.html' %}
{% load static %}


{% block title %}
{{ block.super }}
{% endblock title %}

{% block content %}

<div class="container-fluid bg-light min-vh-100">
    <div class="container-fluid pt-2 bg-body max-width-1000px min-vh-100">
        <div class="row">
            <div class="col">
                <!-- Форма -->
                <p>Вы вышли!</p>

                <a href="{% url 'custom_auth:login'%}">Нажмите сюда что бы зайти снова.</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

custom_auth/templates/custom_auth/login.html
{% extends 'python_exercise/base.html' %}
{% load static %}


{% block title %}
{{ block.super }}
{% endblock title %}

{% block head %}
<!-- Для авторизации через VK -->
<script src="https://vk.com/js/api/openapi.js?169" type="text/javascript"></script>
{% endblock head %}

{% block content %}
<!-- Для авторизации через VK -->
<script type="text/javascript">
    VK.init({ apiId: 8113311 });
</script>

<div class="container-fluid bg-light d-flex flex-grow-1">
    <div class="container-fluid pt-2 bg-body max-width-1000px flex-grow-1">
        <div class="row">
            <div class="col">
                <h6 class="text-center ">
                    <span class="fs-2">
                        Вход
                    </span>
                    /
                    <a href="{% url 'custom_auth:registration' %}" class="link-primary" style="text-decoration: none;">
                        Регистрация
                    </a>
                </h6>
                <!-- Форма -->
                <form method="post" class="max-width-300px my-0 mx-auto">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                    <div class="alert alert-danger mt-3" role="alert">{{ form.non_field_errors }}</div>
                    {% endif %}


                    <div class="mb-3">
                        <label for="{{ form.username.id_for_label }}" class="form-label">
                            {{ form.username.label }}
                        </label>
                        {{ form.username }}

                        {% if form.username.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ form.username.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.password.id_for_label }}" class="form-label">
                            {{ form.password.label }}
                        </label>
                        {{ form.password }}
                        {% if form.password.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ form.password.errors }}</div>
                        {% endif %}
                    </div>
                    <input class="form-check-input" type="checkbox" value="" id="show-password">
                    <label class="form-check-label" for="show-password">
                        Показать пароль
                    </label>

                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                    <div>
                        <button id='submit' type="submit" class="btn btn-primary my-1 px-4" style="width: max-content">
                            Вход
                        </button>
                    </div>
                    <div class="text-center my-2">
                        <a href="{% url 'custom_auth:password_reset' %}" class="link-secondary">Сбросить пароль?</a>
                    </div>
                </form>
                {% if login_vk_error %}
                <div class="alert alert-warning mx-auto" style="width: max-content">
                    Ошибка авторизации через VK
                </div>
                {% endif %}
                <div id="vk_auth" class="mx-auto mb-2"></div>
                <script id="vk_auth_script" type="text/javascript">
                    VK.Widgets.Auth('vk_auth', { authUrl: "{% url 'custom_auth:login_vk' %}" });
                </script>

            </div>
        </div>
    </div>
</div>
<script>
    var input = document.getElementById("password");
    var button = document.getElementById("show-password");
    button.onclick = show;

    function show() {
        if (input.getAttribute('type') == 'password') {
            input.removeAttribute('type');
            input.setAttribute('type', 'text');
            // button.innerHTML = 'Hide password';

        } else {
            input.removeAttribute('type');
            input.setAttribute('type', 'password');
            // button.innerHTML = 'Show password';

        }
    }
</script>

{% endblock content %}

custom_auth/templates/custom_auth/password_reset_complete.html
{% extends "python_exercise/base.html" %}

{% block title %}
{{ block.super }}
{% endblock title %}

{% block content %}

<!--Password Reset Complete-->
<div class="container-fluid bg-light d-flex flex-grow-1">
    <div class="container-fluid pt-2 bg-body max-width-1000px flex-grow-1">
        <div class="row">
            <div class="col">
                <div class="container p-4">
                    <h2 class="font-weight-bold mt-3">Сброс пароля завершен</h2>
                    <hr>
                    <p>Теперь вы можете попробовать войти</p>
                    <a href="{% url 'custom_auth:login' %}" class="btn btn-primary">Войти</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

custom_auth/templates/custom_auth/password_reset_confirm.html
{% extends "python_exercise/base.html" %}


{% block title %}
{{ block.super }}
{% endblock title %}


{% block content %}

{% if validlink %}
<div class="container-fluid bg-light d-flex flex-grow-1">
    <div class="container-fluid pt-2 bg-body max-width-1000px flex-grow-1">
        <div class="row">
            <div class="col">
                <p>Пожалуйста придумайте новый пароль и подтвердите его.</p>
                <form action="" method="post" class="max-width-300px my-0 mx-auto">
                    <div style="display:none">
                        <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.new_password1.id_for_label }}" class="form-label">
                            {{ form.new_password1.label_tag }}
                        </label>
                        {{ form.new_password1 }}

                        {% if form.new_password1.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ form.new_password1.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.new_password2.id_for_label }}" class="form-label">
                            {{ form.new_password2.label_tag }}
                        </label>
                        {{ form.new_password2 }}

                        {% if form.new_password2.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ form.new_password2.errors }}</div>
                        {% endif %}
                    </div>
                    <button id='submit' type="submit" class="btn btn-primary my-1 px-4" style="width: max-content">
                        Принять
                    </button>
                </form>
                {% else %}
                <h1>Ошибка сброса пароля</h1>
                <p> Ссылка на сброс пароля не действительна, возможно потому что она используется повторно. Пожалуйста
                    сделайте
                    новый
                    запрос на сброс пароля.
                </p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

custom_auth/templates/custom_auth/password_reset_done.html
{% extends "python_exercise/base.html" %}


{% block content %}

<!--Password reset sent-->
<div class="container p-5">
    <h2 class="font-weight-bold mt-3">Password reset sent</h2>
    <hr>
    <p>
        Вам отправлено письмо с инструкцие по восстановлению вашего пароля. <br>Если вы не получили письмо, убедитель
        что вы вбили правильный адрес электронной почты, а также проверьте раздел со спаммом вашего почтового клиента.
    </p>
</div>

{% endblock %}

custom_auth/templates/custom_auth/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktranslate %}
Вы получили данное сообщение потому что оставили запрос на восстановление пароля аккаунта для сайта
{{site_name }}.{% endblocktranslate %}

{% translate "Пожалуйста перейдите по ссылке и выберете новый пароль:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'custom_auth:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Ваше имя пользователя на случай если вы забыли:' %} {{ user.get_username }}

{% translate "Спасибо за использование нашего сайта!" %}

{% blocktranslate %}Команда {{ site_name }}
{% endblocktranslate %}

{% endautoescape %}

custom_auth/templates/custom_auth/password_reset_form.html
{% extends 'python_exercise/base.html' %}

{% block title %}
{{ block.super }}
{% endblock title %}

{% block content %}

<div class="container-fluid bg-light min-vh-100">
    <div class="container-fluid pt-2 bg-body max-width-1000px min-vh-100">
        <div class="row">
            <div class="col">
                <h4 class="text-center">Сброс пароля</h4>
                <!-- Форма -->
                <form method="post" class="max-width-300px my-0 mx-auto">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                    <div class="alert alert-danger mt-3" role="alert">{{ form.non_field_errors }}</div>
                    {% endif %}

                    {% for field in form %}
                    <div class="mb-3 max-width-300px">
                        <label for="{{ field.id_for_label }}" class="form-label">
                            {{ field.label }}
                        </label>
                        {{ field }}
                        {% if field.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ field.errors }}</div>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Принять</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

custom_auth/templates/custom_auth/registration.html
{% extends 'python_exercise/base.html' %}
{% load static %}


{% block title %}
{{ block.super }}
{% endblock title %}

{% block content %}

<div class="container-fluid bg-light min-vh-100">
    <div class="container-fluid pt-2 bg-body max-width-1000px min-vh-100">
        <div class="row">
            <div class="col">
                <h6 class="text-center ">
                    <span class="fs-2">
                        Регистрация
                    </span>
                    /
                    <a href="{% url 'custom_auth:login' %}" class="link-primary" style="text-decoration: none;">
                        Вход
                    </a>
                </h6>
                <!-- Форма -->
                <form method="post" class="max-width-300px my-0 mx-auto">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                    <div class="alert alert-danger mt-3" role="alert">{{ form.non_field_errors }}</div>
                    {% endif %}


                    <div class="mb-3">
                        <label for="{{ form.username.id_for_label }}" class="form-label">
                            {{ form.username.label }}
                        </label>
                        {{ form.username }}

                        {% if form.username.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ form.username.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.password1.id_for_label }}" class="form-label">
                            {{ form.password1.label }}
                        </label>
                        {{ form.password1 }}

                        {% if form.password1.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ form.password1.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.password2.id_for_label }}" class="form-label">
                            {{ form.password2.label }}
                        </label>
                        {{ form.password2 }}

                        {% if form.password2.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ form.password2.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.first_name.id_for_label }}" class="form-label">
                            {{ form.first_name.label }}
                        </label>
                        {{ form.first_name }}

                        {% if form.first_name.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ form.first_name.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.last_name.id_for_label }}" class="form-label">
                            {{ form.last_name.label }}
                        </label>
                        {{ form.last_name }}

                        {% if form.last_name.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ form.last_name.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.email.id_for_label }}" class="form-label">
                            {{ form.email.label }}
                        </label>
                        {{ form.email }}
                        <div class="">* - обязательные поля </div>

                        {% if form.email.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ form.email.errors }}</div>
                        {% endif %}
                    </div>

                    <input type="hidden" name="next" value="{{ next }}">
                    <div class="wrapper-submit">
                        <button id='submit' type="submit" class="btn btn-primary my-1 px-4">
                            Создать
                        </button>
                    </div>


                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}