chat/urls.py
from django.urls import path
from .views import index, room

urlpatterns = [
    path('', index, name='index'),
    path('<str:room_name>/', room, name='room'),
]

custom_auth/urls.py
from django.urls import path
from .views import *


app_name = 'custom_auth'

urlpatterns = [
    path('registration/',
         RegistrationUserView.as_view(),
         name='registration'),

    path('login/vk/',
         login_vk,
         name='login_vk'),

    path('login/<str:error>',
         CustomLoginView.as_view(),
         name='login_error'),

    path('login/',
         CustomLoginView.as_view(),
         name='login'),

    path('logout/',
         CustomLogoutView.as_view(),
         name='logout'),

    path('password_reset/',
         CustomPasswordResetView.as_view(),
         name='password_reset'),

    path('reset/<uidb64>/<token>/',
         CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('reset/done/',
         CustomPasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('reset/complete/',
         CustomPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

]

demidovsite/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import *
from python_exercise.views import *

# from rest_framework import routers
# from .views import UserViewSet, GroupViewSet


# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
# router.register(r'groups', GroupViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('custom_auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('python_exercise.urls')),
    path('api-auth',
         include('rest_framework.urls', namespace='rest_framework')),
    path('rest/', include('snippets.urls')),
    path('chat/', include('chat.urls')),
]


# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = page_not_found

python_exercise/urls.py
from django.urls import include, path, re_path
from .views import *
from django.views.generic.base import RedirectView
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView

app_name = 'python_exercise'

urlpatterns = [
    path('',
         ShowExercises.as_view(),
         name='home'),

    path('tag/<slug:tag_slug>/',
         ShowExercises.as_view(),
         name='tag'),

    path('category/<slug:category_slug>/',
         ShowExercises.as_view(),
         name='category'),

    path('category/<slug:category_slug>/tag/<slug:tag_slug>',
         ShowExercises.as_view(),
         name='category_and_tag'),

    path('create-exercise/',
         CreateExercise.as_view(),
         name='create-exercise'),

    path('create-tag/',
         create_tag,
         name='create-tag'),

    path('update-exercise/<int:exercise_id>/',
         UpdateExercise.as_view(),
         name='update-exercise'),

    path('exercise/<int:exercise_id>/',
         ShowComments.as_view(),
         name='exercise'),

    path('user/exercises/<slug:username>/',
         ShowUserExercises.as_view(),
         name='user_exercises'),

    path('user/exercises/create/<slug:username>/',
         ShowUserExercisesCreate.as_view(),
         name='user_exercises_create'),

    path('user/exercises/update/<slug:username>/',
         ShowUserExercisesUpdate.as_view(),
         name='user_exercises_update'),

    path('set-timezone/',
         set_timezone,
         name='set_timezone'),

]

python_exercise/forms.py
from django import forms
from .models import *
from .views import *
from django.contrib.auth.forms import UserCreationForm
from .utils import *


class ExerciseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_published'].required = True
        self.fields['is_published'].initial = True
        self.fields['category'].empty_label = "Категория не выбрана"

    class Meta:
        model = Exercise
        fields = ['title', 'task_text', 'is_published', 'category', 'tag']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'task_text': forms.Textarea(
                attrs={'class': 'form-control'}),
            'is_published': forms.CheckboxInput(
                attrs={'class': 'form-check-input'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
            'tag': forms.SelectMultiple(
                attrs={'class': 'form-control'}),
        }

    def clean_task_text(self):
        task_text = self.cleaned_data['task_text']
        clean_task_text = clean_data_from_js(task_text)
        return clean_task_text


class CreateTagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name', 'slug']

python_exercise/views.py
import json
from pprint import pprint

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.serializers import serialize
from django.db.models import Q
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.views.decorators.vary import vary_on_headers
from django.views.decorators.http import condition

from .forms import *
from .forms import CreateTagForm, ExerciseForm
from .models import *
from .utils import *


alphabet = {'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i',
            'й': 'j', 'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't',
            'у': 'u', 'ф': 'f', 'х': 'kh', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'shch', 'ы': 'i', 'э': 'e', 'ю': 'yu',
            'я': 'ya'}


def slugify_rus(s):
    """
    Overriding django slugify that allows to use russian words as well.
    """
    return slugify(''.join(alphabet.get(w, w) for w in s.lower()))


@ method_decorator(vary_on_headers('Cookie'), name='dispatch')
@ method_decorator(cache_page(60 * 15), name='dispatch')
# @ method_decorator(condition(etag_func=lambda _: 'v1'), name='dispatch')
class ShowExercises(DataMixin, ListView):
    model = Exercise
    template_name = 'python_exercise/index.html'
    context_object_name = 'exercises'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        current_category_slug = self.kwargs.get('category_slug')

        current_tag_slug = self.kwargs.get('tag_slug')

        if current_category_slug:
            context['current_category'] = Category.objects.get(
                slug=current_category_slug)
            context['title'] = context['current_category'].name
        else:
            context['title'] = 'Все категории'

        if current_tag_slug:
            context['current_tag'] = Tag.objects.get(
                slug=current_tag_slug)
            context['title'] += ' #' + context['current_tag'].name

        context['categories'] = Category.objects.all()
        context['tags'] = Tag.objects.all()

        return context

    def get_queryset(self):
        current_category_slug = self.kwargs.get('category_slug')

        current_tag_slug = self.kwargs.get('tag_slug')

        exercises = []

        if current_category_slug and current_tag_slug:
            db_query = {
                'category__slug': current_category_slug,
                'tag__slug': current_tag_slug
            }
        elif current_category_slug:
            db_query = {
                'category__slug': current_category_slug,
            }
        elif current_tag_slug:
            db_query = {
                'tag__slug': current_tag_slug
            }
        else:
            db_query = {}

        exercises = (Exercise.objects
                     .filter(**db_query)
                     .select_related('category', 'author_create', 'author_update')
                     .prefetch_related('tag'))
        return exercises


class ShowUserExercises(LoginRequiredMixin, ShowExercises):
    slug_url_kwarg = 'username'
    template_name = 'python_exercise/user-exercises.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.request.user.username
        first_name = self.request.user.first_name
        last_name = self.request.user.last_name
        if first_name:
            context['title'] = f'Задачи от {first_name} {last_name} ({username})'
        else:
            context['title'] = f'Задачи от {username}'

        return context

    def get_queryset(self):
        query_author_create = Q(author_create=self.request.user)
        query_author_update = Q(author_update=self.request.user)

        exercises = (Exercise.objects
                     .filter(query_author_create | query_author_update)
                     .select_related('category', 'author_create', 'author_update')
                     .prefetch_related('tag'))
        return exercises


class ShowUserExercisesCreate(ShowUserExercises):
    def get_queryset(self):
        query_author_create = Q(author_create=self.request.user)

        exercises = (Exercise.objects
                     .filter(query_author_create)
                     .select_related('category', 'author_create', 'author_update')
                     .prefetch_related('tag'))
        return exercises


class ShowUserExercisesUpdate(ShowUserExercises):
    def get_queryset(self):
        query_author_update = Q(author_update=self.request.user)

        exercises = (Exercise.objects
                     .filter(query_author_update)
                     .select_related('category', 'author_create', 'author_update')
                     .prefetch_related('tag'))
        return exercises


class ShowTag(Index):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категория'
        return context

    def get_queryset(self):
        return Tag.objects.get(slug=self.kwargs['tag_slug']).exercise_set.all()


class CreateExercise(LoginRequiredMixin, DataMixin, CreateView):
    form_class = ExerciseForm
    template_name = 'python_exercise/create-update-exercise.html'
    login_url = reverse_lazy('custom_auth:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Добавление задачи'
        context['categories'] = Category.objects.all()
        context['tags'] = Tag.objects.all()

        context['submit_name'] = 'Создать'

        return context

    def form_valid(self, form):
        form.instance.author_create = self.request.user
        form.instance.author_update = self.request.user
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('python_exercise:exercise', args=(self.object.id,))


@require_POST
def create_tag(request):
    # if request.method != 'POST':
    #     return redirect('python_exercise:home', permanent=True)

    if not request.user.is_authenticated:
        return redirect('custom_auth:login', permanent=True)

    body_unicode = request.body.decode('utf-8')
    body = json.loads(body_unicode)

    data = body
    data['slug'] = slugify_rus(data['name'])
    form = CreateTagForm(data)
    if form.is_valid():
        try:
            Tag.objects.create(**form.cleaned_data)
            tags = Tag.objects.all()
            tags_json = serialize('json', tags)
            response = {
                'error': 'Null',
                'tags': tags_json
            }
        except:
            error = f"Тег с таким именем({form.cleaned_data['tag_name']}) уже существует"
            response = {
                'error': error,
                'tags': 'Null'
            }
    else:
        error = form.errors
        response = {
            'error': error,
            'tags': 'Null'
        }

    return JsonResponse(response)


class UpdateExercise(LoginRequiredMixin, DataMixin, UpdateView):
    model = Exercise
    form_class = ExerciseForm
    template_name = 'python_exercise/create-update-exercise.html'
    pk_url_kwarg = 'exercise_id'
    login_url = reverse_lazy('custom_auth:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование задачи'
        context['categories'] = Category.objects.all()
        context['tags'] = Tag.objects.all()

        context['cur_url_name'] = f"{context['cur_url_name']}/{self.kwargs['exercise_id']}"
        context['submit_name'] = 'Сохранить'
        return context

    def form_valid(self, form):
        form.instance.author_update = self.request.user
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('python_exercise:exercise', args=(self.object.id,))


class ShowComments(DataMixin, DetailView):
    model = Exercise
    template_name = 'python_exercise/exercise-discussion.html'
    pk_url_kwarg = 'exercise_id'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['exercise'] = get_object_or_404(
            Exercise.objects.select_related('author_create', 'author_update'),
            id=self.kwargs['exercise_id'])

        context['title'] = context['exercise'].title
        return context


def page_not_found(request, exception):
    return HttpResponse('<h1> Страница не найдена </h1>')


def set_timezone(request):

    if request.method != 'POST':
        print('<' + request.POST['next'] + '>')
        return redirect(request.POST['next'], permanent=True)

    if request.method == 'POST':
        print(request.POST['timezone'])
        request.session['django_timezone'] = request.POST['timezone']
        return redirect(request.POST['next'], permanent=True)

python_exercise/templates/create-update-exercise.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{{ block.super }}
{% endblock title %}

{% block content %}

<div class="container-fluid min-vh-100">
    <div class="container-fluid pt-2 bg-body max-width-1000px min-vh-100">
        <div class="page-header">
            <h4 class="text-center" style="z-index:-10">{{ title }}</h4>
        </div>
        <div class="row">
            <div class="col">
                <!-- Форма -->
                <form id="create-exercise" method="post" class="max-width-900px mx-auto">
                    {% csrf_token %}
                    {% if new_exercise %}
                    <div class="alert alert-success mt-2 mb-1" role="alert">
                        Задача добавлена!
                    </div>
                    {% endif %}

                    <div class="mb-3 max-width-300px">
                        <label for="{{ form.title.id_for_label }}" class="form-label">
                            {{ form.title.label }}
                        </label>
                        {{ form.title }}

                        {% if form.title.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ form.title.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="mb-3 max-width-900px">
                        <label for="{{ form.task_text.id_for_label }}" class="form-label">
                            {{ form.task_text.label }}
                        </label>
                        {{ form.task_text }}

                        {% if form.task_text.errors %}
                        <div class="alert alert-danger mt-3" role="alert">{{ form.task_text.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="mb-3 max-width-300px mt-2">
                        <label for="{{ form.is_published.id_for_label }}" class="form-label me-1">
                            {{ form.is_published.label }}
                        </label>
                        {{ form.is_published }}
                    </div>

                    <div class="mb-3 max-width-300px mt-2">
                        <label for="{{ form.category.id_for_label }}" class="form-label me-1">
                            {{ form.category.label }}
                        </label>
                        {{ form.category }}
                    </div>

                    <label id="labelTags" for="{{ form.tag.id_for_label }}" class="form-label"
                        data-create-tag-url="{% url 'python_exercise:create-tag' %}">{{ form.tag.label }}</label>
                    <div class="tag-wrapper d-flex align-items-center mt-2">
                        <input class="form-control max-width-300px input_tag_real me-2" list="datalistOptions"
                            placeholder="Выберите тег">
                        <datalist id="datalistOptions">
                            {% for tag in tags %}
                            <option class="option_tag_real" value="{{ tag.name }}">
                                {% endfor %}
                        </datalist>

                        <img role="button" src="{% static 'python_exercise/img/plus.svg' %}" height="24px" alt="">
                    </div>
                    {{ form.tag }}
                    <div class="alert alert-danger mt-3" role="alert" id="tag-error" hidden>{{ form.tag.errors }}</div>

                    <button id='submit' type="submit" class="btn btn-primary my-3">
                        {{ submit_name }}
                    </button>

                </form>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.tiny.cloud/1/rscqscrtyr7mlho06zt9i0k4ugf0bwhhcey86hqx5i9wir99/tinymce/5/tinymce.min.js"
    referrerpolicy="origin"></script>
<script defer src="{% static 'python_exercise/js/create-update-exercise.js' %}"></script>

{% endblock content %}

python_exercise/templates/exercise-discussion.html
{% extends 'base.html' %}
{% load pagination_tag %}


{% block title %}
{{ block.super }}
{% endblock title %}

{% block head %}
<!-- Для комментариев через vk -->
<script src="https://vk.com/js/api/openapi.js?169" type="text/javascript"></script>
{% endblock head %}

{% block content %}
{% load static %}

<div class="container-fluid h-100">
    <div class="row flex-nowrap h-100">
        <!-- Боковая панель -->
        {% load sidebar_categories_tag %}
        {% sidebar_categories_tag %}
        <!-- Основное содержание -->
        <main class="col ps-md-2 pt-2 h-100 max-width-1000px bg-body mx-auto">

            <div class="content" id="content">
                <div class="row  ">
                    <div class="container-fluid text-left relative">
                        <div class="page-header">
                            <h2 class="text-center" style="z-index:-10">{{ title }}</h2>
                        </div>
                        <hr>
                        <div class="col-12">
                            {% include 'exercise.html' %}
                            <hr>
                        </div>
                    </div>
                </div>


                <div id="vk_comments" style="width: 100%; height: 500px"></div>
                <script type="text/javascript">
                    VK.init({
                        apiId: 8113311
                    });
                    VK.Widgets.Comments('vk_comments', {
                        limit: 10,
                        attach: "*",
                        pageURL: window.location.pathname
                    });
                </script>
        </main>
    </div>
</div>
{% endblock content %}

python_exercise/templates/index.html
{% extends 'base.html' %}
{% load pagination_tag %}

{% block title %}
{{ block.super }}
{% endblock title %}

{% block content %}
{% load static %}

<div class="container-fluid h-100">
    <div class="row flex-nowrap h-100">
        <!-- Боковая панель -->
        {% load sidebar_categories_tag %}
        {% sidebar_categories_tag %}
        <!-- Основное содержание -->
        <main class="col ps-md-2 pt-2 h-100 max-width-1000px bg-body mx-auto">

            <div class="content" id="content">
                <div class="row  ">
                    <div class="container-fluid text-left relative">
                        <a class="btn btn-body text-dark d-flex align-items-center" data-bs-toggle="collapse"
                            href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample"
                            style="box-shadow: none; width: min-content">
                            <span class="d-inline-block me-2 ">
                                Теги
                            </span>
                            <img src="{% static 'python_exercise/img/arrow_down.svg' %}" style="height: 18px" alt="">
                        </a>
                        <div class="collapse" id="collapseExample">
                            <ul class="list-group">
                                {% for tag in tags %}
                                <li class="list-group-item border-0">
                                    <a class="text-dark" href="
                                        {% if current_category %}
                                        {% url 'python_exercise:category_and_tag' category_slug=current_category.slug tag_slug=tag.slug %}
                                        {% else %}
                                        {% url 'python_exercise:tag' tag_slug=tag.slug %}
                                        {% endif %}">
                                        #{{ tag.name }}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="page-header">
                            <h2 class="text-center" style="z-index:-10">{{ title }}</h2>
                            {% if current_tag %}
                            <h6 class="text-center" style="z-index:-10">#{{ current_tag.name }}</h6>
                            {% endif %}
                        </div>
                        <hr>

                        <div class="col-12">
                            {% for exercise in exercises %}
                            {% include 'exercise.html' %}
                            <hr>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row max-width-1000px mx-auto mb-2">
                        <div class="col-12">
                            {% pagination_tag %}
                        </div>
                    </div>
                </div>
        </main>
    </div>
</div>
{% endblock content %}

python_exercise/templates/menu_tag.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <!-- Иконка с переходом на главную -->
        <a class="navbar-brand fs-2 lh-1 px-2 m-auto" href="{% url 'python_exercise:home' %}">
            {% load static %}
            <img src="{% static 'python_exercise/img/favicon.svg' %}" height='48px' alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link 
                    {% if cur_url_name == 'create-exercise' %}                   
                    active
                    {% endif %}" href="{% url 'python_exercise:create-exercise' %}">
                        {{ menu.create_exercise.title }}
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link 
                    {% if cur_url_name == 'user_exercises' %}                   
                    active
                    {% endif %}" href="{% url 'python_exercise:user_exercises' username=user.username %}">
                        {{ menu.user_exercises.title }}
                    </a>
                </li>

                {% endif %}

            </ul>
            <!-- Кнопки справа -->
            <ul class="navbar-nav mb-2 mb-lg-0">
                {% if user.is_authenticated %}

                <li class="nav-item">
                    <span class="nav-link me-2 my-1">
                        {{ user.first_name }} {{ user.last_name }} ({{ user.username }})
                        {% if user.userdata %}
                        <img class="rounded-circle ms-2" src="{{ user.userdata.photo_url }}" alt="фото_нет"
                            style="height: 30px">
                        {% endif %}
                    </span>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-success my-1" href="{% url 'custom_auth:logout' %}">
                        {{ menu.logout.title }}
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="btn btn-outline-success my-1" href="{% url 'custom_auth:login' %}">
                        {{ menu.login.title }}
                    </a>
                </li>
                {% endif %}
            </ul>

        </div>

    </div>
</nav>

python_exercise/templates/user-exercises.html
{% extends 'base.html' %}
{% load pagination_tag %}


{% block title %}
{{ block.super }}
{% endblock title %}

{% block content %}
{% load static %}

<div class="container-fluid h-100">
    <div class="row flex-nowrap h-100">
        <!-- Боковая панель -->
        {% load sidebar_categories_tag %}
        {% sidebar_categories_tag %}
        <!-- Основное содержание -->
        <main class="col ps-md-2 pt-2 h-100 max-width-1000px bg-body mx-auto">

            <div class="content" id="content">
                <div class="row  ">
                    <div class="container-fluid text-left relative">
                        <a class="btn btn-body text-dark d-flex align-items-center" data-bs-toggle="collapse"
                            href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample"
                            style="box-shadow: none; width: min-content">
                            <span class="d-inline-block me-2 ">
                                Теги
                            </span>
                            <img src="{% static 'python_exercise/img/arrow_down.svg' %}" style="height: 18px" alt="">
                        </a>
                        <div class="collapse" id="collapseExample">
                            <ul class="list-group">
                                {% for tag in tags %}
                                <li class="list-group-item border-0">
                                    <a class="text-dark" href="
                                        {% if current_category %}
                                        {% url 'python_exercise:category_and_tag' category_slug=current_category.slug tag_slug=tag.slug %}
                                        {% else %}
                                        {% url 'python_exercise:tag' tag_slug=tag.slug %}
                                        {% endif %}">
                                        #{{ tag.name }}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>


                        <div class="page-header">
                            <h2 class="text-center" style="z-index:-10">{{ title }}</h2>

                            <h6 class="text-center ">

                                {% if cur_url_name == 'user_exercises' %}
                                <span>Все</span>
                                {% else %}
                                <a href="{% url 'python_exercise:user_exercises' username=user.username %}"
                                    class="link-primary" style="text-decoration: none;">
                                    Все
                                </a>
                                {% endif %}
                                /
                                {% if cur_url_name == 'user_exercises_create' %}
                                <span>Я автор</span>
                                {% else %}
                                <a href="{% url 'python_exercise:user_exercises_create' username=user.username %}"
                                    class="link-primary" style="text-decoration: none;">
                                    Я автор
                                </a>
                                {% endif %}
                                /
                                {% if cur_url_name == 'user_exercises_update' %}
                                <span>Я последний редактор</span>
                                {% else %}
                                <a href="{% url 'python_exercise:user_exercises_update' username=user.username %}"
                                    class="link-primary" style="text-decoration: none;">
                                    Я последний редактор
                                </a>
                                {% endif %}

                            </h6>
                        </div>

                        <hr>

                        <div class="col-12">
                            {% for exercise in exercises %}
                            {% include 'exercise.html' %}
                            <hr>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row max-width-1000px mx-auto mb-2">
                        <div class="col-12">
                            {% pagination_tag %}
                        </div>
                    </div>
                </div>
        </main>
    </div>
</div>
{% endblock content %}